spring:
  threads:
    virtual:
      enabled: true
  logging:
    level:
      web: debug
  application:
    name: ecsOrder
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecshopdb}
    username: ${DB_USER:ecuser}
    password: ${DB_PASSWORD:changeMe}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#  session:
#    redis:
#      flush-mode: on_save
#      namespace: spring:session
#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      password: ${REDIS_PASSWORD:changeMe}
#      port: ${REDIS_PORT:6379}
server:
  servlet:
    session:
      timeout: 2m
      cookie:
        http-only: true
#        secure: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
  #        allowed-origins: https//
  #        allowed-methods: GET
  endpoint:
    health:
      show-details: always
    env:
      cache:
        time-to-live: 10s
#      roles: ADMIN
logging:
  level:
    org.springframework.security: trace
    .org:
      springframework:
        security:
          web:
            context:
              HttpSessionSecurityContextRepository: TRACE
        session: DEBUG
app:
  upload:
    dir: "uploads"
