spring:
  application:
    name: ecsOrder-test

  datasource:
    url: jdbc:postgresql://localhost:59588/testdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    session:
      timeout: 2m
      cookie:
        http-only: true

app:
  upload:
    dir: "uploads"