spring:
  application:
    name: <YOUR_APPLICATION_NAME>
  datasource:
    url: <YOUR_DB_URL>
    username: <YOUR_DB_USERNAME>
    password: <YOUR_DB_USER_PASSWORD>
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Might not be necessary

server:
  servlet:
    session:
      timeout: 30m # Adjust to your preferences, lower for testing
      cookie:
        http-only: true
#        secure: true

logging:
  level:
    org.springframework.security: trace
    .org:
      springframework:
        security:
          web:
            context:
              HttpSessionSecurityContextRepository: TRACE
        session: DEBUG